services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
    kafka:
        #build: ./kafka
        image: kafka
        depends_on: 
            - zookeeper
        ports:
            - "19092:19092"
        environment:
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,CONNECTIONS_FROM_HOST://localhost:19092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
            KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONNECTIONS_FROM_HOST://0.0.0.0:19092
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        links:
            - zookeeper
    phoebus-alarm-server:
        #build: ./phoebus-alarm-server
        image: phoebus-alarm-server
        links:
            - kafka
            - example-ioc
        depends_on: 
            - kafka
        volumes:
            - "./examples/heart_of_gold/heart_of_gold.xml:/tmp/nalms/heart_of_gold.xml"
        command: start-server HeartOfGold /tmp/nalms/heart_of_gold.xml
        environment:
            - KAFKA_BOOTSTRAP=kafka:9092
    phoebus-alarm-logger:
        image: phoebus-alarm-logger
       # build: ./phoebus-alarm-logger
        links:
            - elasticsearch
        depends_on:
            - elasticsearch
        volumes:
            - "./examples/heart_of_gold/heart_of_gold.xml:/tmp/nalms/heart_of_gold.xml"
        command: start-logger HeartOfGold /tmp/nalms/heart_of_gold.xml
    elasticsearch:
        #build: ./elasticsearch
        image: elasticsearch
        ports:
            - "9200:9200"
        environment:
        - node.name=node01
        - cluster.name=es-cluster-7
        - discovery.type=single-node
        - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
        - ES_HOST=localhost
        - ES_PORT=9200
    grafana:
        build: ./grafana
        ports:
            - '3000:3000'
        links:
            - elasticsearch
    example-ioc:
        #build: ./examples/heart_of_gold
        image: heart_of_gold
        ports:
            - '127.0.0.1:5064:5064'
            - '127.0.0.1:5065:5065'
            - '127.0.0.1:5064:5046/udp'
        environment:
            - EPICS_CA_SERVER_PORT=5064
    cruise-control:
        image: cruise-control
       # build: ./cruise-control
        ports: 
            - "9090:9090"
        links: 
            - kafka
            - zookeeper
    
        
    

    # cruise control?
