services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
    kafka:
        image: jgarrahan/nalms-kafka:latest
        depends_on: 
            - zookeeper
        ports:
            - "19092:19092"
        environment:
            BROKER_ID: 0
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,CONNECTIONS_FROM_HOST://localhost:19092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
            KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONNECTIONS_FROM_HOST://0.0.0.0:19092
            ZOOKEEPER_CONNECT: zookeeper:2181
        volumes:
            - "./kafka/config/server.properties:/opt/kafka/server.properties"
        links:
            - zookeeper
        deploy:
            resources:
                limits:
                    cpus: 0.50
                    memory: 8G
                reservations:
                    memory: 8G
    kafka1:
        image: jgarrahan/nalms-kafka:latest
        depends_on: 
            - zookeeper
        ports:
            - "19093:19093"
        environment:
            BROKER_ID: 1
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,CONNECTIONS_FROM_HOST://localhost:19093
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
            KAFKA_LISTENERS: PLAINTEXT://kafka1:9092,CONNECTIONS_FROM_HOST://0.0.0.0:19093
            ZOOKEEPER_CONNECT: zookeeper:2181
        volumes:
            - "./kafka/config/server.properties:/opt/kafka/server.properties"
        links:
            - zookeeper
        deploy:
            resources:
                limits:
                    cpus: 0.50
                    memory: 8G
                reservations:
                    memory: 8G
    kafka2:
        image: jgarrahan/nalms-kafka:latest
        depends_on: 
            - zookeeper
        ports:
            - "19094:19094"
        environment:
            BROKER_ID: 2
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092,CONNECTIONS_FROM_HOST://localhost:19094
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
            KAFKA_LISTENERS: PLAINTEXT://kafka2:9092,CONNECTIONS_FROM_HOST://0.0.0.0:19094
            ZOOKEEPER_CONNECT: zookeeper:2181
        volumes:
            - "./kafka/config/server.properties:/opt/kafka/server.properties"
        links:
            - zookeeper
        deploy:
            resources:
                limits:
                    cpus: 0.50
                    memory: 8G
                reservations:
                    memory: 8G
    phoebus-alarm-server:
        image: jgarrahan/nalms-phoebus-alarm-server:latest
        links:
            - kafka
            - example-ioc
        depends_on: 
            - kafka
        volumes:
            - "./examples/heart_of_gold/heart_of_gold.xml:/tmp/nalms/heart_of_gold.xml"
            - "./phoebus-alarm-server/config/alarm_server.properties:/opt/nalms/config/alarm_server.properties"
            - "./phoebus-alarm-server/config/logging.properties:/opt/nalms/config/logging.properties"
        command: start-server HeartOfGold /tmp/nalms/heart_of_gold.xml
        environment:
            KAFKA_BOOTSTRAP: kafka:9092
            EPICS_CA_ADDR_LIST: alarm-ioc example-ioc
            ALARM_IOC: "true"
    elasticsearch:
        image: jgarrahan/nalms-elasticsearch:latest
        ports:
            - "9200:9200"
        environment:
            node.name: node01
            cluster.name: es-cluster-7
            discovery.type: single-node
            ES_JAVA_OPTS: "-Xms128m -Xmx128m"
            ES_HOST: localhost
            ES_PORT: 9200
    grafana:
        image: jgarrahan/nalms-grafana:latest
        ports:
            - '3000:3000'
        links:
            - elasticsearch
        volumes:
            - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    phoebus-alarm-logger:
        image: jgarrahan/nalms-phoebus-alarm-logger
        links:
            - elasticsearch
        depends_on:
            - elasticsearch
            - kafka
            - phoebus-alarm-server
        volumes:
            - "./examples/heart_of_gold/heart_of_gold.xml:/tmp/nalms/heart_of_gold.xml"
            - "./phoebus-alarm-logger/config/alarm_logger.properties:/opt/nalms/config/alarm_logger.properties"
            - "./phoebus-alarm-logger/config/logging.properties:/opt/nalms/config/logging.properties"
        command: start-logger HeartOfGold /tmp/nalms/heart_of_gold.xml
    example-ioc:
        image: jgarrahan/nalms-example-ioc:latest
        image: heart_of_gold
        ports:
            - "5065:5065/tcp"
            - "5064:5064/tcp"
            - "5065:5065/udp"
            - "5064:5064/udp"
        environment:
            EPICS_CA_SERVER_PORT: 5064
    cruise-control:
        image: jgarrahan/nalms-cruise-control:latest
        ports: 
            - "9090:9090"
        volumes:
            - "./cruise-control/cruisecontrol.properties:/opt/cruise-control/config/cruisecontrol.properties"
        links: 
            - kafka
            - zookeeper
    phoebus-client:
        image: jgarrahan/nalms-phoebus-client:latest
        environment:
            - DISPLAY=host.docker.internal:0
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - ./phoebus-client/phoebus.properties:/opt/phoebus/phoebus.properties
        depends_on:
            - kafka
            - elasticsearch
        deploy:
            resources:
                limits:
                    memory: 4g
    alarm-ioc:
        image: alarm-ioc
        environment:
            CONFIG_NAME: HeartOfGold
            EPICS_CA_SERVER_PORT: 5064
            EPICS_CA_REPEATER_PORT: 5065
        volumes:
            - "./examples/heart_of_gold/alarm-ioc:/opt/nalms/ioc"
        ports:
            - "5067:5065/tcp"
            - "5066:5064/tcp"
            - "5067:5065/udp"
            - "5066:5064/udp"
