site_name: NALMS
repo_url: https://github.com/slaclab/nalms/
site_url: https://slaclab.github.io/nalms
nav:
  - Overview: index.md
  - Introduction: introduction.md
  - Install: install.md
  - Legacy: legacy.md
  - Components:
      - components.md
      - Kafka: kafka.md


markdown_extensions:
  - toc:
      toc_depth: 4