site_name: NALMS
repo_url: https://github.com/slaclab/nalms/

nav:
  - introduction.md
  - Install: install.md
  - Legacy: legacy.md
  - Components:
      - components.md
      - Kafka: kafka.md

theme:
  name: 'material'

markdown_extensions:
  - codehilite  
  
plugins:
    - search