site_name: NALMS
repo_url: https://github.com/slaclab/nalms/

nav:
  - index.md
  - Installation: install.md
  - Legacy: legacy.md
  - Components:
      - components.md
      - Kafka: kafka.md
      - Phoebus Alarm Tools: phoebus.md
      - Tools: tools.md
  - Configuration: configuration.md
  - EPICS Integration: epics_integration.md
  - Development: development.md
  - Networking: networking.md
  - Demo: demo.md
  - CLI: cli.md

theme:
  name: 'material'

markdown_extensions:
  - codehilite  
  
plugins:
    - search