apiVersion: 1

datasources:
  - name: AlarmState
    type: elasticsearch
    access: proxy
    database: "demo_*"
    url: http://{HOST_IP}:{ELASTICSEARCH_PORT}
    jsonData:
      esVersion: 60
      timeField: "time"
      logMessageField: "_id"
