apiVersion: 1

datasources:
  - name: HeartOfGold
    type: elasticsearch
    access: proxy
    database: "demo_*"
    url: http://elasticsearch:9200
    jsonData:
      esVersion: 60
      timeField: "message_time"
      logMessageField: "id"
