services:
  phoebus-client:
    image: phoebus-client
#    build: .
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    deploy:
        resources:
            limits:
                memory: 8g