name: Build docs

on:
  push:
    branches:
      - main
      - github-actions
jobs:
  build:
    if: ${{ github.repository == 'slaclab/nalms' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
    name:  Build docs
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: true
          conda-build-version: 3.18.11
          python-version: ${{ matrix.python-version }}
          channels: anaconda,conda-forge
          channel-priority: flexible
      - name: Build package
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda install --file dev-requirements.txt
          conda install --file docs-requirements.txt
          mkdocs build
          mkdocs gh-deploy --force